# Generated by Django 4.2.21 on 2025-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('published', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True)),
                ('link', models.URLField(unique=True)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
